# Practice 7. NumPy

In [1]:
import numpy as np
from pprint import pprint

## Low level

### Task 1

In [2]:
res = np.fromfunction(lambda x,y: (x+y)%2 ,(8,8), dtype=int)
pprint(res)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)


### Task 2

In [3]:
res = np.fromfunction(lambda x,y: np.array((x/4, y/4)), (5,5))
res = res.T.reshape((25,2))
res = np.array(list(map(tuple, res)), dtype=np.dtype('float,float'))
res = res.reshape((5,5))
print(res)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


### Task3

In [4]:
res = np.random.rand(10,2)
x,y = res[:,0], res[:,1]
res[:, 0] = np.sqrt(x**2+y**2)
res[:, 1] = np.arctan2(y,x)
print(res)

[[0.59877044 0.75179305]
 [1.16458835 0.47821338]
 [0.81105866 0.62661873]
 [0.78012701 0.15681913]
 [1.14905892 0.60113841]
 [0.7340492  0.67370521]
 [0.35001298 0.77761012]
 [1.2079766  0.56060393]
 [0.73634801 0.72588253]
 [1.1214026  0.60533971]]


### Task 4

In [5]:
X = list(range(1,7))
A = 2.4685
array = np.array(X)
print(array[np.abs(array-A).argmin()])

2


### Task 5

In [6]:
a = np.arange(21).reshape((3, 7))
mean = np.mean(a, axis=1).reshape((3,1))
ones = np.ones(a.shape)
a - mean * ones

array([[-3., -2., -1.,  0.,  1.,  2.,  3.],
       [-3., -2., -1.,  0.,  1.,  2.,  3.],
       [-3., -2., -1.,  0.,  1.,  2.,  3.]])

### Task 6

In [7]:
elements = np.random.rand(10)
zeros= np.zeros((5,5)).reshape((25))
zeros[:len(elements)] = elements
np.random.shuffle(zeros)
res = zeros.reshape((5,5))
res

array([[0.        , 0.        , 0.        , 0.18902111, 0.        ],
       [0.31763871, 0.01086294, 0.66929786, 0.51133958, 0.42894558],
       [0.        , 0.        , 0.        , 0.1923804 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.63384939, 0.        , 0.60433353, 0.        , 0.23131721]])

### Task 7

In [8]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
x = np.zeros((max(I)+1))
for idx_el,i in enumerate(I):
    x[i]+=X[idx_el]
x

array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

## Medium Level

### Task 1

In [9]:
a = np.random.rand(5,5)
print('Before: ')
pprint(a)
print('#'*75)
row_idx = 3,2
a[row_idx[0]], a[row_idx[1]] = a[row_idx[1]], a[row_idx[0]].copy()
print('AFTER: ')
pprint(a)
print('#'*75)

Before: 
array([[1.29795918e-01, 2.17521351e-01, 2.55977764e-01, 6.89210698e-01,
        1.22415118e-01],
       [1.52853820e-01, 7.79640534e-01, 5.48117252e-01, 4.59994956e-01,
        6.13511326e-01],
       [2.67663995e-01, 7.49176257e-01, 6.67542524e-01, 9.68108023e-02,
        8.19969337e-01],
       [5.01329594e-01, 7.43450383e-01, 6.54085190e-01, 2.23513923e-01,
        2.80681251e-01],
       [7.96344604e-04, 9.62597397e-01, 5.77629028e-01, 5.10237048e-01,
        7.19391431e-01]])
###########################################################################
AFTER: 
array([[1.29795918e-01, 2.17521351e-01, 2.55977764e-01, 6.89210698e-01,
        1.22415118e-01],
       [1.52853820e-01, 7.79640534e-01, 5.48117252e-01, 4.59994956e-01,
        6.13511326e-01],
       [5.01329594e-01, 7.43450383e-01, 6.54085190e-01, 2.23513923e-01,
        2.80681251e-01],
       [2.67663995e-01, 7.49176257e-01, 6.67542524e-01, 9.68108023e-02,
        8.19969337e-01],
       [7.96344604e-04, 9.6259739

### Task 2

In [10]:
shape = (5,5)

# generate array
a = np.zeros((shape[0]*shape[1],))
data = np.random.rand(10)
a[:10] = data
np.random.shuffle(a)
a = a.reshape(shape)
a[:,3] = np.zeros(shape[1])
print(a)


# processing 
res = np.argwhere(a == 0)[:,1]
cnt = np.bincount(res)
result_index = np.where(cnt == shape[1])[0]
print(f'zero columns: {result_index}')

[[0.47275947 0.         0.40673603 0.         0.53331257]
 [0.52619755 0.         0.62246008 0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.31398921 0.         0.        ]
 [0.         0.09020428 0.         0.         0.        ]]
zero columns: [3]


### Task 3

In [11]:
a = [1, 2, 3, 4, 5]
delta = 3
def f(i):
    return i + delta * (i)
new_len = len(a)*(delta+1) - delta
idx = np.fromfunction(f, (5,), dtype=int)
res = np.zeros((new_len,))
res[idx] = a
res

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

### Task 4

In [12]:
X = ([1, 2, 3], [4, 5], [6, 7])

arrays = [np.asarray(array) for array in X]
lens_of_arrays = np.indices(map(len, arrays))
lens_of_arrays = lens_of_arrays.reshape(len(arrays), -1).T
res = np.zeros_like(lens_of_arrays)

for idx, arr in enumerate(arrays):
    res[:, idx] = arr[lens_of_arrays[:, idx]]
    
res

array([[1, 4, 6],
       [1, 4, 7],
       [1, 5, 6],
       [1, 5, 7],
       [2, 4, 6],
       [2, 4, 7],
       [2, 5, 6],
       [2, 5, 7],
       [3, 4, 6],
       [3, 4, 7],
       [3, 5, 6],
       [3, 5, 7]])

### Task 5

In [13]:
def moving_average(array, n):
    len_of_new_arr = array.shape[0] - (n - 1)
    result = np.zeros(len_of_new_arr)
    for idx in range(len_of_new_arr):
        result[idx] = np.average(array[idx:idx+n])
    return result

Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


## Advanced Level

### Task 1

In [14]:
a = np.random.rand(2,2,2,2)
res = a.sum( axis = (-2,-1))
print(a)
res

[[[[0.95995444 0.9628879 ]
   [0.35499199 0.72764724]]

  [[0.00825946 0.59324128]
   [0.15506735 0.69666902]]]


 [[[0.56219671 0.86243063]
   [0.73296999 0.40328864]]

  [[0.6816768  0.92878645]
   [0.18329175 0.39809893]]]]


array([[3.00548157, 1.45323711],
       [2.56088597, 2.19185393]])

### Task 2

In [15]:
shape = (16,16)
a = np.random.randint(0,2,(*shape, 3), dtype=np.ubyte)
res = a[...,0]*256*256 + a[...,1]*256 + a[...,2]
len(np.unique(res))

4

### Task 3

In [16]:
from scipy.spatial import distance
a = np.random.rand(100,2)
res = distance.cdist(a,a)
res

array([[0.        , 0.94007211, 0.79101154, ..., 0.21462528, 0.58186959,
        0.94220669],
       [0.94007211, 0.        , 0.31602143, ..., 0.93100125, 1.1363969 ,
        0.03625448],
       [0.79101154, 0.31602143, 0.        , ..., 0.8534885 , 0.8522903 ,
        0.34642126],
       ...,
       [0.21462528, 0.93100125, 0.8534885 , ..., 0.        , 0.79580737,
        0.92483818],
       [0.58186959, 1.1363969 , 0.8522903 , ..., 0.79580737, 0.        ,
        1.15654436],
       [0.94220669, 0.03625448, 0.34642126, ..., 0.92483818, 1.15654436,
        0.        ]])

### Task 4

In [17]:
def distance(p, P0, P1):
    delta = P1-P0
    lenght = (delta ** 2).sum(axis = 1)
    dist = -((P0[:,0]-p[...,0])*delta[:,0] + (P0[:,1]-p[...,1])*delta[:,1]) / lenght
    dist = dist.reshape(len(dist),1)
    return np.sqrt(((P0 + dist*delta -p)**2).sum(axis=1)) 


p = np.random.uniform(0,10,(7,2))
P0 = np.random.uniform(0,10,(7,2))
P1 = np.random.uniform(0,10,(7,2))
print(f"p = {p}")
print(f"P0 = {P0}")
print(f"P1 = {P1}")
print("Distance = ",distance(p, P0, P1))

p = [[4.45578308 1.87963907]
 [6.36114409 6.36929243]
 [8.50281186 4.53919994]
 [1.45109207 4.57356089]
 [5.67737546 6.19508306]
 [4.44072744 7.3270896 ]
 [9.12417222 3.93522716]]
P0 = [[9.42823635 0.22655457]
 [8.76865754 4.82615913]
 [7.48265587 9.78409238]
 [2.3572959  1.32767922]
 [6.82008974 9.79798299]
 [9.38532491 0.44616437]
 [0.89742507 5.52797877]]
P1 = [[5.63612445 3.27098683]
 [6.91933577 3.14670578]
 [9.76201944 2.90139253]
 [4.73511344 1.45772421]
 [3.89120803 3.74937991]
 [0.45290938 5.97136528]
 [9.63150448 6.45713252]]
Distance =  [1.82390137 2.76090965 0.68046558 3.29052531 0.54172901 3.25078004
 2.45408637]


### Task 5

In [18]:
def get_binary(x):
    return list(np.binary_repr(x, width=8))
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
res_list = np.array(list(map(get_binary,I)),dtype=int)
print(res_list)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
