# Practice 7. NumPy

In [2]:
import numpy as np
from pprint import pprint

## Low level

### Task 1

In [3]:
res = np.fromfunction(lambda x,y: (x+y)%2 ,(8,8), dtype=int)
pprint(res)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)


### Task 2

In [4]:
res = np.fromfunction(lambda x,y: np.array((x/4, y/4)), (5,5))
res = res.T.reshape((25,2))
res = np.array(list(map(tuple, res)), dtype=np.dtype('float,float'))
res = res.reshape((5,5))
print(res)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


### Task3

In [5]:
res = np.random.rand(10,2)
x,y = res[:,0], res[:,1]
res[:, 0] = np.sqrt(x**2+y**2)
res[:, 1] = np.arctan2(y,x)
print(res)

[[1.09974667 0.52915086]
 [0.90518058 0.35929805]
 [0.70402064 0.78477779]
 [0.692082   0.7713466 ]
 [0.83910268 0.74454212]
 [0.74987693 0.11543642]
 [0.38541355 0.77136481]
 [1.13933078 0.69527442]
 [1.17401381 0.56294071]
 [1.00383131 0.24251397]]


### Task 4

In [6]:
X = list(range(1,7))
A = 2.4685
array = np.array(X)
print(array[np.abs(array-A).argmin()])

2


### Task 5

In [7]:
a = np.arange(21).reshape((3, 7))
mean = np.mean(a, axis=1).reshape((3,1))
ones = np.ones(a.shape)
a - mean * ones

array([[-3., -2., -1.,  0.,  1.,  2.,  3.],
       [-3., -2., -1.,  0.,  1.,  2.,  3.],
       [-3., -2., -1.,  0.,  1.,  2.,  3.]])

### Task 6

In [8]:
elements = np.random.rand(10)
zeros= np.zeros((5,5)).reshape((25))
zeros[:len(elements)] = elements
np.random.shuffle(zeros)
res = zeros.reshape((5,5))
res

array([[0.54705514, 0.        , 0.04236035, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.85712648, 0.        ],
       [0.        , 0.        , 0.        , 0.87173327, 0.17021438],
       [0.        , 0.91097487, 0.        , 0.        , 0.20980842],
       [0.62154371, 0.29435467, 0.        , 0.51821322, 0.        ]])

### Task 7

In [9]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
x = np.zeros((max(I)+1))
for idx_el,i in enumerate(I):
    x[i]+=X[idx_el]
x

array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

## Medium Level

### Task 1

In [10]:
a = np.random.rand(5,5)
print('Before: ')
pprint(a)
print('#'*75)
row_idx = 3,2
a[row_idx[0]], a[row_idx[1]] = a[row_idx[1]], a[row_idx[0]].copy()
print('AFTER: ')
pprint(a)
print('#'*75)

Before: 
array([[0.57768871, 0.40965763, 0.11204369, 0.4833966 , 0.11572839],
       [0.34234818, 0.11703676, 0.05320172, 0.56577924, 0.11809645],
       [0.83598526, 0.67236159, 0.37297267, 0.8632396 , 0.81657417],
       [0.4490289 , 0.17604774, 0.60666992, 0.62730594, 0.79319833],
       [0.71576801, 0.45036643, 0.17075879, 0.65817052, 0.74523167]])
###########################################################################
AFTER: 
array([[0.57768871, 0.40965763, 0.11204369, 0.4833966 , 0.11572839],
       [0.34234818, 0.11703676, 0.05320172, 0.56577924, 0.11809645],
       [0.4490289 , 0.17604774, 0.60666992, 0.62730594, 0.79319833],
       [0.83598526, 0.67236159, 0.37297267, 0.8632396 , 0.81657417],
       [0.71576801, 0.45036643, 0.17075879, 0.65817052, 0.74523167]])
###########################################################################


### Task 2

In [44]:
shape = (5,5)

# generate array
a = np.zeros((shape[0]*shape[1],))
data = np.random.rand(10)
a[:10] = data
np.random.shuffle(a)
a = a.reshape(shape)
a[:,3] = np.zeros(shape[1])
print(a)


# processing 
res = np.argwhere(a == 0)[:,1]
cnt = np.bincount(res)
result_index = np.where(cnt == shape[1])[0]
print(f'zero columns: {result_index}')

[[0.42919985 0.29555047 0.         0.         0.48636845]
 [0.99762471 0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.51258559 0.         0.         0.        ]
 [0.         0.46216394 0.         0.         0.        ]]
zero columns: [2 3]


### Task 3

In [12]:
a = [1, 2, 3, 4, 5]
delta = 3
def f(i):
    return i + delta * (i)
new_len = len(a)*(delta+1) - delta
idx = np.fromfunction(f, (5,), dtype=int)
res = np.zeros((new_len,))
res[idx] = a
res

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

### Task 4

In [13]:
X = ([1, 2, 3], [4, 5], [6, 7])

arrays = [np.asarray(array) for array in X]
lens_of_arrays = np.indices(map(len, arrays))
lens_of_arrays = lens_of_arrays.reshape(len(arrays), -1).T
res = np.zeros_like(lens_of_arrays)

for idx, arr in enumerate(arrays):
    res[:, idx] = arr[lens_of_arrays[:, idx]]
    
res

array([[1, 4, 6],
       [1, 4, 7],
       [1, 5, 6],
       [1, 5, 7],
       [2, 4, 6],
       [2, 4, 7],
       [2, 5, 6],
       [2, 5, 7],
       [3, 4, 6],
       [3, 4, 7],
       [3, 5, 6],
       [3, 5, 7]])

### Task 5

In [14]:
def moving_average(array, n):
    len_of_new_arr = array.shape[0] - (n - 1)
    result = np.zeros(len_of_new_arr)
    for idx in range(len_of_new_arr):
        result[idx] = np.average(array[idx:idx+n])
    return result

Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


## Advanced Level

### Task 1

In [15]:
a = np.random.rand(2,2,2,2)
res = a.sum( axis = (-2,-1))
print(a)
res

[[[[0.39315797 0.74045724]
   [0.64501618 0.71996455]]

  [[0.60486263 0.43236663]
   [0.81616726 0.87945822]]]


 [[[0.18594877 0.95421768]
   [0.7429538  0.90854151]]

  [[0.59462992 0.0450754 ]
   [0.64548852 0.84444432]]]]


array([[2.49859594, 2.73285473],
       [2.79166175, 2.12963816]])

### Task 2

In [91]:
shape = (16,16)
a = np.random.randint(0,2,(*shape, 3), dtype=np.ubyte)
res = I[...,0]*256*256 + I[...,1]*256 + I[...,2]
len(np.unique(res))

4

### Task 3

In [17]:
from scipy.spatial import distance
a = np.random.rand(100,2)
res = distance.cdist(a,a)
res

array([[0.        , 0.85977812, 0.17516107, ..., 0.8189419 , 0.20400476,
        0.40410728],
       [0.85977812, 0.        , 0.68756076, ..., 0.16565059, 0.69356362,
        0.72262069],
       [0.17516107, 0.68756076, 0.        , ..., 0.65757075, 0.07734851,
        0.31336669],
       ...,
       [0.8189419 , 0.16565059, 0.65757075, ..., 0.        , 0.68189712,
        0.764078  ],
       [0.20400476, 0.69356362, 0.07734851, ..., 0.68189712, 0.        ,
        0.23695201],
       [0.40410728, 0.72262069, 0.31336669, ..., 0.764078  , 0.23695201,
        0.        ]])

### Task 4

In [139]:
def distance(p, P0, P1):
    delta = P1-P0
    lenght = (delta ** 2).sum(axis = 1)
    dist = -((P0[:,0]-p[...,0])*delta[:,0] + (P0[:,1]-p[...,1])*delta[:,1]) / lenght
    dist = dist.reshape(len(dist),1)
    return np.sqrt(((P0 + dist*delta -p)**2).sum(axis=1)) 


p = np.random.uniform(0,10,(7,2))
P0 = np.random.uniform(0,10,(7,2))
P1 = np.random.uniform(0,10,(7,2))
print(f"p = {p}")
print(f"P0 = {P0}")
print(f"P1 = {P1}")
print("Distance = ",distance(p, P0, P1))

p = [[5.06132189 4.02236776]
 [9.02664001 6.97742882]
 [3.43027482 9.19335311]
 [6.41662866 7.63595755]
 [5.02194749 5.28594522]
 [7.74193489 5.865291  ]
 [0.25185775 3.41186996]]
P0 = [[5.26764178 7.90048768]
 [5.7924938  0.73534358]
 [0.36376448 4.51694372]
 [7.11357431 8.68100049]
 [6.3751379  9.98650553]
 [3.90079891 1.49740195]
 [5.85853485 5.3500433 ]]
P1 = [[0.9821597  6.21749845]
 [4.95977024 7.16305117]
 [9.33875992 8.73316033]
 [3.77091627 8.18664613]
 [4.67605559 6.62095109]
 [3.5413382  9.56627734]
 [9.32416007 4.23251648]]
Distance =  [3.53431754 4.00931628 2.92877023 0.93183432 0.91042167 4.03172254
 3.56532527]


### Task 5

In [41]:
def get_binary(x):
    return list(np.binary_repr(x, width=8))
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
res_list = np.array(list(map(get_binary,I)),dtype=int)
print(res_list)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
